
name: Sezen Yağmur Önol
title: Sezen Yağmur Önol
subtitle:  PhD
description: > # this means to ignore newlines until "baseurl:"
     Website about Sezen Yağmur Önol
markdown: kramdown
future: true

     
gems:
    - jekyll-sitemap
    - jekyll-coffeescript
    - jekyll-paginate
    - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  
google_analytics: G-1TJGEYXBPW
